# ~/.config/tmuxinator/beamjobs.yml

name: beamjobs
root: ~/

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks

# Runs on project start, always
on_project_start: echo "Starting BeamJobs development environment..."

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from tmux session )
on_project_exit: echo "Shutting down BeamJobs development environment..."

# Run on project stop
# on_project_stop: command

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux. This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

windows:

  - :
      root: ~/Src/beamjobs-frontend
      pre_window: |
        nvm use 18
      panes:
        - nvim .

  - :
      root: ~/Src/beamjobs-frontend
      layout: main-horizontal
      pre_window: |
        nvm use 18
        npm install
        source .beamspace
      panes:
        - npm run start
        - ngrok http 8888 --subdomain bjclient-mike

  - :
        root: ~/Src/beamjobs-frontend

  - :
      root: ~/Src/beamjobs-backend
      panes:
        - nvim .

  - :
      root: ~/Src/beamjobs-backend
      pre_window: |
        source .beamspace
      layout: main-vertical
      panes:
        - startServer
        - export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES &&  startPublicWorker
        - ngrok http 8888 --subdomain bjserver-mike
        - startPrivateWorker
        
  - :
        root: ~/Src/beamjobs-backend

  - :
      root: ~/
